# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 19:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monopolyprobability', '0002_remove_property_owned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owned', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='property',
            name='owned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monopolyprobability.Owned'),
        ),
    ]
