# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monopolyprobability', '0003_auto_20151204_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owned',
            name='owned',
        ),
        migrations.RemoveField(
            model_name='property',
            name='owned',
        ),
        migrations.AddField(
            model_name='owned',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='monopolyprobability.Property'),
        ),
        migrations.AddField(
            model_name='owned',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ManyToManyField(through='monopolyprobability.Owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
